
"""Manejo de excepciones"""
"""Analizando el comportamiento del try except"""

try:
    val1 = 2/2
except:
    print("Entr贸 al except, ha ocurrido una excepci贸n")
else:
    print("Entr贸 al else, no ha ocurrido ninguna exepci贸n")
